options:
  ksql-release-channel:
    type: string
    default: stable
    description: The release channel of the ksql-server snap package. This will be ignored if the snap file is attached as a resource or built with the charm.
  ksql-cluster-id:
    type: string
    default: development
    description: The KSQL cluster id that the KSQL server will be assigned to.
  use-ssl:
    type: boolean
    default: true
    description: Should KSQL connect to Kafka via SSL or plaintext
  ksql-should-listen-private:
    type: boolean
    default: false
    description: Should KSQL listen on private ip address